name: valorant
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  equatable:
  flutter_bloc:
  http:
  lottie:
  connectivity_plus:
  flutter_spinkit:
  just_audio:
  url_launcher:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
   - assets/lotties/
   - assets/images/
   - assets/music/


  fonts:
    - family: Valorant
      fonts:
        - asset: assets/fonts/valorant_font.ttf

